# Generated by Django 4.0.7 on 2022-09-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='home',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='longtite'),
        ),
    ]
