# Generated by Django 4.0.7 on 2022-09-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_album_owner_photo_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='album',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='longtite'),
        ),
    ]
