# Generated by Django 4.0.7 on 2022-09-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_album_lat_album_lng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='album',
            name='lng',
        ),
        migrations.AddField(
            model_name='photo',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='photo',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='longtite'),
        ),
    ]
